import type { ChatMessage } from "../types";
import { Markdown } from "./Markdown";
import { Chart } from "./Chart";

function sourceLink(src: string): string | null {
  const [kind, id] = src.split(":");
  if (kind === "campaign_id") return `https://www.nhtsa.gov/recalls?nhtsaId=${id}`;
  return null;
}

/**
 * A branded, print-optimized report of one answer. Shown as a full-screen light overlay
 * (so recharts can measure + paint) and printed to PDF via the browser. `print:static`
 * lets it flow across multiple pages when printed. The app shell is `print:hidden`.
 */
export function ReportView({ message }: { message: ChatMessage }) {
  const date = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <div className="fixed inset-0 z-50 overflow-auto bg-white text-slate-900 print:static print:overflow-visible">
      <div className="mx-auto max-w-[800px] px-10 py-10">
        <header className="flex items-start justify-between border-b border-slate-300 pb-4">
          <div>
            <span className="rounded bg-emerald-100 px-2 py-0.5 text-[11px] font-semibold uppercase tracking-wide text-emerald-700">
              NHTSA · RV
            </span>
            <h1 className="mt-2 text-xl font-bold tracking-tight">RV Defect Intelligence — Safety Report</h1>
          </div>
          <div className="whitespace-nowrap pt-1 text-right text-xs text-slate-500">{date}</div>
        </header>

        {message.question && (
          <div className="mt-5">
            <div className="text-[11px] font-semibold uppercase tracking-wide text-slate-500">Question</div>
            <p className="mt-0.5 text-sm font-medium">{message.question}</p>
          </div>
        )}

        <div className="mt-4">
          <Markdown>{message.content}</Markdown>
        </div>

        {message.charts?.map((c, i) => <Chart key={i} spec={c} />)}

        {!!message.sources?.length && (
          <section className="mt-6 break-inside-avoid border-t border-slate-200 pt-3">
            <div className="mb-1 text-[11px] font-semibold uppercase tracking-wide text-slate-500">
              Sources ({message.sources.length}) — verify at nhtsa.gov/recalls
            </div>
            <ul className="grid grid-cols-2 gap-x-8 gap-y-0.5 text-xs sm:grid-cols-3">
              {message.sources.map((s) => {
                const href = sourceLink(s);
                return (
                  <li key={s} className="font-mono text-slate-700">
                    {href ? (
                      <a href={href} className="text-blue-700 underline">
                        {s}
                      </a>
                    ) : (
                      s
                    )}
                  </li>
                );
              })}
            </ul>
          </section>
        )}

        <footer className="mt-8 border-t border-slate-200 pt-3 text-[10px] leading-snug text-slate-400">
          Generated by RV Defect Intelligence · Data source: NHTSA Office of Defects Investigation (ODI),
          refreshed weekly · {date}. Complaints reflect unverified consumer reports; recalls are official
          campaigns. Verify all campaign / ODI numbers at nhtsa.gov/recalls.
        </footer>
      </div>
    </div>
  );
}
